GET http://localhost:3000/painting/

###

POST http://localhost:3000/painting/
Content-Type: application/json  

{
    "name": "The Serene Garden",
    "category": "Landscape",
    "medium": "Acrylic on Canvas",
    "size": "24x36 inches",
    "colour": "Green and Blue",
    "order": 1000,
    "imageUrl": "https://example.com/images/serene_garden.jpg"
}

###

GET http://localhost:3000/painting/6837342c4567eb1567b9952c

###


DELETE http://localhost:3000/painting/6837342c4567eb1567b9952c

###

PATCH http://localhost:3000/painting/683739eacce9d71595dc3f05
Content-Type: application/json

{
    "name": "testpainting"
}